name: Build Theme
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
        working-directory: ./src
      - name: Build  the theme
        working-directory: ./src
        run: npm run build
